run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - goimports
    - revive
    - govet
    - staticcheck
    - lll

linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    enable:
      - shadow
  revive:
    rules:
      - name: unused-parameter
        disabled: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0