// Code generated by protoc-gen-stormrpc. DO NOT EDIT.

package pb

import (
	context "context"
	fmt "fmt"
	stormrpc "github.com/actatum/stormrpc"
)

// EchoerClient is the client API for Echoer service.
type EchoerClient interface {
	Echo(ctx context.Context, in *EchoRequest) (*EchoResponse, error)
}

type echoerClient struct {
	c *stormrpc.Client
}

func NewEchoerClient(c *stormrpc.Client) EchoerClient {
	return &echoerClient{c}
}

func (c *echoerClient) Echo(ctx context.Context, in *EchoRequest) (*EchoResponse, error) {
	var out EchoResponse
	r, err := stormrpc.NewRequest("rpc.Echoer.Echo", in, stormrpc.WithEncodeProto())
	if err != nil {
		return nil, err
	}

	resp := c.c.Do(ctx, r)
	if resp.Err != nil {
		return nil, resp.Err
	}

	if err = resp.Decode(&out); err != nil {
		return nil, err
	}

	return &out, nil
}

// EchoerServer is the server API for Echoer service.
type EchoerServer interface {
	Echo(context.Context, *EchoRequest) (*EchoResponse, error)
}

func RegisterEchoerServer(s *stormrpc.Server, srv EchoerServer) {
	for _, handler := range echoerHandlers {
		handler.SetService(srv)
		s.Handle(handler.Route(), handler.HandlerFunc())
	}
}

type _Echoer_Echo_Handler struct {
	route string
	svc   interface{}
}

func (h *_Echoer_Echo_Handler) HandlerFunc() stormrpc.HandlerFunc {
	return func(ctx context.Context, r stormrpc.Request) stormrpc.Response {
		var in EchoRequest
		if err := r.Decode(&in); err != nil {
			return stormrpc.NewErrorResponse(r.Reply, fmt.Errorf("error decoding request"))
		}

		out, err := h.svc.(EchoerServer).Echo(ctx, &in)
		if err != nil {
			return stormrpc.NewErrorResponse(r.Reply, err)
		}

		resp, err := stormrpc.NewResponse(r.Reply, out, stormrpc.WithEncodeProto())
		if err != nil {
			return stormrpc.NewErrorResponse(r.Reply, err)
		}

		return resp
	}
}
func (h *_Echoer_Echo_Handler) Route() string {
	return h.route
}
func (h *_Echoer_Echo_Handler) SetService(svc interface{}) {
	h.svc = svc
}

type handler interface {
	Route() string
	HandlerFunc() stormrpc.HandlerFunc
	SetService(interface{})
}

var echoerHandlers = []handler{
	&_Echoer_Echo_Handler{route: "rpc.Echoer.Echo"},
}
